#xtranslate ;
VGraph(TROW <a> TCOL <b> BROW <c> BCOL <d> PRCNT <e> [FCHAR <f>] [BCHAR <g>] [FCOLOR <h>] [BCOLOR <i>] [FINAL <j>] [ZERO <k>])=>;
_BarGraphV(<a>,<b>,<c>,<d>,<e>,<f>,<g>,<h>,<i>,<j>,<k>)

#xtranslate ;
HGraph( TROW <a> TCOL <b> BROW <c> BCOL <d> PRCNT <e> [FCHAR <f>] [BCHAR <g>] [FCOLOR <h>] [BCOLOR <i>] [FINAL <j>] [ZERO <k>] ) => ;
_BarGraphH(<a>,<b>,<c>,<d>,<e>,<f>,<g>,<h>,<i>,<j>,<k>)

#xtranslate ;
  OF: <caseof> => UPPER(SUBSTR(mtext,i,1)) = '<caseof>'

